server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        rewrite ^/api/(.*) /discovery/uk/restaurants/enriched/bypostcode/$1 break;
        proxy_pass https://uk.api.just-eat.io;
        proxy_set_header Host uk.api.just-eat.io;
        proxy_ssl_server_name on;
    }
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}